    <p><span class="biblat"><acronym title="{_('Bibliografía Latinoamericana')}">Biblat</acronym></span>: {_('fuente bibliométrica para conocer la productividad científica de América Latina y el Caribe')}</p>
		          
    <p><span class="biblat"><acronym title="{_('Bibliografía Latinoamericana')}">Biblat</acronym></span> <?php _printf('es un portal especializado en la generación de frecuencias e indicadores bibliométricos de las bases de datos %s (Citas Latinoamericanas en Ciencias Sociales y Humanidades) y %s (Índice de Revistas Latinoamericanas en Ciencias), el cual ha sido concebido como una fuente de información que permite conocer las características de la producción científica de América Latina y el Caribe publicada en revistas académicas de la región. Para tal fin, %s conjunta y sistematiza la información contenida en %s y %s, las bases de datos bibliográficas con el conjunto más representativo e incluyente de revistas académicas publicadas en América Latina y el Caribe (más de 3 mil revistas y más de 700,000 registros bibliográficos entre ambas bases). Por otra parte, dichas bases de datos cuentan con una','<a href="http://clase.unam.mx" target="_blank"><acronym title="'._sprintf('Citas Latinoamericanas en Ciencias Sociales y Humanidades').'">CLASE</acronym></a>','<a href="http://periodica.unam.mx" target="_blank"><acronym title="'._sprintf('Índice de Revistas Latinoamericanas en Ciencias').'">PERIÓDICA</acronym></a>','<span class="biblat"><acronym title="'._sprintf('Bibliografía Latinoamericana').'">Biblat</acronym></span>','<a href="http://clase.unam.mx" target="_blank"><acronym title="'._sprintf('Citas Latinoamericanas en Ciencias Sociales y Humanidades').'">CLASE</acronym></a>','<a href="http://periodica.unam.mx" target="_blank"><acronym title="'._sprintf('Índice de Revistas Latinoamericanas en Ciencias').'">PERIÓDICA</acronym></a>');?> <a href="{site_url("clase-y-periodica")}" target="_blank">{_('cobertura multidisciplinaria en todas las áreas del conocimiento.')}</a></p>

    <p><?php _printf('La muestra de las frecuencias e indicadores bibliométricos aportados por %s está conformada por las publicaciones de América Latina y el Caribe y sus correspondientes registros bibliográficos indizados en %s y %s. Las revistas y registros bibliográficos indizados por base de datos son:','<span class="biblat"><acronym title="'._sprintf('Bibliografía Latinoamericana').'">Biblat</acronym></span>','<a href="http://clase.unam.mx" target="_blank"><acronym title="'._sprintf('Citas Latinoamericanas en Ciencias Sociales y Humanidades').'">CLASE</acronym></a>','<a href="http://periodica.unam.mx" target="_blank"><acronym title="'._sprintf('Índice de Revistas Latinoamericanas en Ciencias').'">PERIÓDICA</acronym></a>');?></p>

    <p><?php _printf('La selección de las publicaciones seriadas y periódicas que ingresan a las dos bases de datos es realizada por un comité de evaluación y selección conforme los lineamientos contenidos en el "Reglamento del Comité de Evaluación y Selección de Publicaciones Seriadas para las bases de datos %s y %s", en su versión actualizada en abril de 2010. Para consultar los criterios editoriales que se utilizan en la selección de las revistas véase criterios de selección.','<a href="http://clase.unam.mx" target="_blank"><acronym title="'._sprintf('Citas Latinoamericanas en Ciencias Sociales y Humanidades').'">CLASE</acronym></a>','<a href="http://periodica.unam.mx" target="_blank"><acronym title="'._sprintf('Índice de Revistas Latinoamericanas en Ciencias').'">PERIÓDICA</acronym></a>');?></p>

    <p><?php _printf('Tipo de publicación y de documento indizados: en %s y %s se indizan diversos tipos de revistas, las cuales pueden ser clasificadas como revistas de investigación científica, de carácter técnico-profesional y de divulgación científica y cultural. Desde 1997, el Comité de Evaluación y Selección prioriza la inclusión de revistas de investigación científica y humanística, dirigidas a especialistas, así como revistas de comunicación científica, dirigidas a profesionistas, técnicos, estudiantes y profesores. Asimismo, se registran los diversos tipos de documentos que aparecen publicados, tales como son artículos, biografías, conferencias o discursos, correspondencia, cronologías, editorial, ensayos, entrevistas, estadísticas o encuestas, leyes o reglamentos, monografías, notas breves o noticias, proyectos técnicos o programas, reportes técnicos, reseñas de libro y revisiones bibliográficas. Con objeto de realizar un análisis bibliométrico especializado en artículos publicados en revistas con arbitraje por pares, %s ofrece la opción de realizar las distintas búsquedas disponibles aplicadas solamente al universo de revistas con arbitraje y considerando solamente los documentos clasificados como artículos y ensayos.','<a href="http://clase.unam.mx" target="_blank"><acronym title="'._sprintf('Citas Latinoamericanas en Ciencias Sociales y Humanidades').'">CLASE</acronym></a>','<a href="http://periodica.unam.mx" target="_blank"><acronym title="'._sprintf('Índice de Revistas Latinoamericanas en Ciencias').'">PERIÓDICA</acronym></a>','<span class="biblat"><acronym title="'._sprintf('Bibliografía Latinoamericana').'">Biblat</acronym></span>');?></p>

    <p><?php _printf('Consultar lista de revistas arbitradas.');?></p>
