<p><span class="biblat"><acronym title="{_('Bibliografía Latinoamericana')}">Biblat</acronym></span> {_('es un portal especializado en revistas científicas y académicas publicadas en América Latina y el Caribe, que ofrece los siguientes servicios:')}</p>
<ol>
  <li><p>{_sprintf('Referencias bibliográficas de los artículos y documentos publicados en más de 3,000 títulos indizados en <a href="%s">CLASE</a> y %s, mediante opciones de búsqueda básica y avanzada.', 'http://clase.unam.mx', cat '<a href="http://periodica.unam.mx" target="_blank"><acronym title="' _('Índice de Revistas Latinoamericanas en Ciencias') '">PERIÓDICA</acronym></a>')}</p></li>
  
  <li><p><?php _printf('Referencias bibliográficas de los artículos y documentos publicados en más de 3,000 títulos indizados en %s y %s, mediante opciones de búsqueda básica y avanzada.','<a href="http://clase.unam.mx" target="_blank"><acronym title="'._('Citas Latinoamericanas en Ciencias Sociales y Humanidades').'">CLASE</acronym></a>','<a href="http://periodica.unam.mx" target="_blank"><acronym title="'._('Índice de Revistas Latinoamericanas en Ciencias').'">PERIÓDICA</acronym></a>');?></p></li>

  <li><p><?php _printf('Acceso al texto completo de los artículos publicados en revistas de acceso abierto. %s ofrece dos tipos de acceso al texto completo: mediante enlaces hipertextuales a los sitios web de las revistas (recursos externos) y a través de la colección del acervo digital de la Hemeroteca Virtual Latinoamericana de la Dirección General de Bibliotecas %s, Universidad Nacional Autónoma de México %s.','<span class="biblat"><acronym title="'._('Bibliografía Latinoamericana').'">Biblat</acronym></span>','<a href="http://dgb.unam.mx" target="_blank">DGB</a>','<a href="http://www.unam.mx" target="_blank"><acronym title='._('Universidad Nacional Autónoma de México').'">UNAM</acronym></a>');?></p></li>

  <li><p><?php _printf('Frecuencias e %s extraídos de las revistas indizadas en %s y %s, en las colecciones %s así como de otras fuentes de información.','<a href="indicadores" target="_blank">indicadores bibliométricos</a>','<a href="http://clase.unam.mx" target="_blank"><acronym title="'._('Citas Latinoamericanas en Ciencias Sociales y Humanidades').'">CLASE</acronym></a>','<a href="http://periodica.unam.mx" target="_blank"><acronym title="'._('Índice de Revistas Latinoamericanas en Ciencias').'">PERIÓDICA</acronym></a>','<a href="http://www.scielo.org" target="_blank"><acronym title="Scientific Electronic Library Online">SciELO</acronym></a>');?></p></li>

  <li><p><?php _printf('En Postular una revista se describen los Criterios de selección de revistas para su indización en %s y %s, que son la fuente de información principal de %s. Los editores de revistas pueden someter a evaluación su revista dirigiéndose a:','<a href="http://clase.unam.mx" target="_blank"><acronym title="'._('Citas Latinoamericanas en Ciencias Sociales y Humanidades').'">CLASE</acronym></a>','<a href="http://periodica.unam.mx" target="_blank"><acronym title="'._('Índice de Revistas Latinoamericanas en Ciencias').'">PERIÓDICA</acronym></a>','<a href="mailto:biblat@dgb.unam.mx">biblat@dgb.unam.mx</a>');?> <span class="biblat"><acronym title="{_('Bibliografía Latinoamericana')}">Biblat</acronym></span>.</p></li>

  <li><p>{_('En Políticas de acceso se clasifican las revistas de acceso abierto de acuerdo con los permisos de acceso, uso y archivado adoptados por éstas.')}</p></li>
</ol>